// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: builtin/logical/kv/types.proto

package kv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// If values are added to this, be sure to update the config() function
type Configuration struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MaxVersions         uint32                 `protobuf:"varint,1,opt,name=max_versions,json=maxVersions,proto3" json:"max_versions,omitempty"`
	CasRequired         bool                   `protobuf:"varint,2,opt,name=cas_required,json=casRequired,proto3" json:"cas_required,omitempty"`
	DeleteVersionAfter  *durationpb.Duration   `protobuf:"bytes,3,opt,name=delete_version_after,json=deleteVersionAfter,proto3" json:"delete_version_after,omitempty"`
	MetadataCasRequired bool                   `protobuf:"varint,400,opt,name=metadata_cas_required,json=metadataCasRequired,proto3" json:"metadata_cas_required,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_builtin_logical_kv_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_logical_kv_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_builtin_logical_kv_types_proto_rawDescGZIP(), []int{0}
}

func (x *Configuration) GetMaxVersions() uint32 {
	if x != nil {
		return x.MaxVersions
	}
	return 0
}

func (x *Configuration) GetCasRequired() bool {
	if x != nil {
		return x.CasRequired
	}
	return false
}

func (x *Configuration) GetDeleteVersionAfter() *durationpb.Duration {
	if x != nil {
		return x.DeleteVersionAfter
	}
	return nil
}

func (x *Configuration) GetMetadataCasRequired() bool {
	if x != nil {
		return x.MetadataCasRequired
	}
	return false
}

type VersionMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CreatedTime is when the version was created.
	CreatedTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// DeletionTime is the time this version becomes invalid.
	// Set to Now() to delete the version before the configured
	// delete time.
	DeletionTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deletion_time,json=deletionTime,proto3" json:"deletion_time,omitempty"`
	// Destroyed is used to specify this version is
	// a has been removed and the underlying data deleted.
	Destroyed     bool `protobuf:"varint,3,opt,name=destroyed,proto3" json:"destroyed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionMetadata) Reset() {
	*x = VersionMetadata{}
	mi := &file_builtin_logical_kv_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionMetadata) ProtoMessage() {}

func (x *VersionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_logical_kv_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionMetadata.ProtoReflect.Descriptor instead.
func (*VersionMetadata) Descriptor() ([]byte, []int) {
	return file_builtin_logical_kv_types_proto_rawDescGZIP(), []int{1}
}

func (x *VersionMetadata) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *VersionMetadata) GetDeletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTime
	}
	return nil
}

func (x *VersionMetadata) GetDestroyed() bool {
	if x != nil {
		return x.Destroyed
	}
	return false
}

type KeyMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key is the key for this entry
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Versions is the map of versionID -> VersionMetadata.
	// Useful when listing all versions.
	Versions map[uint64]*VersionMetadata `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// CurrentVersion is the latest version of the value
	CurrentVersion uint64 `protobuf:"varint,3,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	// OldestVersion is the oldest version of the value.
	OldestVersion uint64 `protobuf:"varint,4,opt,name=oldest_version,json=oldestVersion,proto3" json:"oldest_version,omitempty"`
	// Created time is when the metadata was created.
	CreatedTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// Updated time was the last time the metadata version
	// was updated.
	UpdatedTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	// MaxVersions specifies how many versions to keep around.
	// If empty value, defaults to the configured Max
	// for the mount.
	MaxVersions uint32 `protobuf:"varint,7,opt,name=max_versions,json=maxVersions,proto3" json:"max_versions,omitempty"`
	// CasRequired specifies if the cas parameter is
	// required for this key
	CasRequired bool `protobuf:"varint,8,opt,name=cas_required,json=casRequired,proto3" json:"cas_required,omitempty"`
	// DeleteVersionAfter specifies how long to keep versions around. If
	// empty value, defaults to the configured delete_version_after for the
	// mount.
	DeleteVersionAfter *durationpb.Duration `protobuf:"bytes,9,opt,name=delete_version_after,json=deleteVersionAfter,proto3" json:"delete_version_after,omitempty"`
	// CustomMetadata is a map of string key-value pairs used to store
	// user-provided information about the secret.
	CustomMetadata map[string]string `protobuf:"bytes,10,rep,name=custom_metadata,json=customMetadata,proto3" json:"custom_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// MetadataCasRequired specifies if the metadata_cas parameter is
	// required for metadata updates, independent of data updates
	MetadataCasRequired bool `protobuf:"varint,400,opt,name=metadata_cas_required,json=metadataCasRequired,proto3" json:"metadata_cas_required,omitempty"`
	// MetadataVersion is a counter for the metadata itself,
	// separate from the content versions
	CurrentMetadataVersion uint64 `protobuf:"varint,401,opt,name=current_metadata_version,json=currentMetadataVersion,proto3" json:"current_metadata_version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *KeyMetadata) Reset() {
	*x = KeyMetadata{}
	mi := &file_builtin_logical_kv_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMetadata) ProtoMessage() {}

func (x *KeyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_logical_kv_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMetadata.ProtoReflect.Descriptor instead.
func (*KeyMetadata) Descriptor() ([]byte, []int) {
	return file_builtin_logical_kv_types_proto_rawDescGZIP(), []int{2}
}

func (x *KeyMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyMetadata) GetVersions() map[uint64]*VersionMetadata {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *KeyMetadata) GetCurrentVersion() uint64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *KeyMetadata) GetOldestVersion() uint64 {
	if x != nil {
		return x.OldestVersion
	}
	return 0
}

func (x *KeyMetadata) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *KeyMetadata) GetUpdatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedTime
	}
	return nil
}

func (x *KeyMetadata) GetMaxVersions() uint32 {
	if x != nil {
		return x.MaxVersions
	}
	return 0
}

func (x *KeyMetadata) GetCasRequired() bool {
	if x != nil {
		return x.CasRequired
	}
	return false
}

func (x *KeyMetadata) GetDeleteVersionAfter() *durationpb.Duration {
	if x != nil {
		return x.DeleteVersionAfter
	}
	return nil
}

func (x *KeyMetadata) GetCustomMetadata() map[string]string {
	if x != nil {
		return x.CustomMetadata
	}
	return nil
}

func (x *KeyMetadata) GetMetadataCasRequired() bool {
	if x != nil {
		return x.MetadataCasRequired
	}
	return false
}

func (x *KeyMetadata) GetCurrentMetadataVersion() uint64 {
	if x != nil {
		return x.CurrentMetadataVersion
	}
	return 0
}

type Version struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data is a JSON object with string keys that
	// represents the user supplied data.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// CreatedTime is when the version was created.
	CreatedTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// DeletionTime is the time this version becomes invalid.
	// Set to Now() to delete the version before the configured
	// deletion time.
	DeletionTime  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deletion_time,json=deletionTime,proto3" json:"deletion_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_builtin_logical_kv_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_logical_kv_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_builtin_logical_kv_types_proto_rawDescGZIP(), []int{3}
}

func (x *Version) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Version) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *Version) GetDeletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTime
	}
	return nil
}

type UpgradeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Started time is when the upgrade was started.
	StartedTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=started_time,json=startedTime,proto3" json:"started_time,omitempty"`
	// done is set to true once the backend has been successfully
	// upgraded.
	Done          bool `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeInfo) Reset() {
	*x = UpgradeInfo{}
	mi := &file_builtin_logical_kv_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeInfo) ProtoMessage() {}

func (x *UpgradeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_logical_kv_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeInfo.ProtoReflect.Descriptor instead.
func (*UpgradeInfo) Descriptor() ([]byte, []int) {
	return file_builtin_logical_kv_types_proto_rawDescGZIP(), []int{4}
}

func (x *UpgradeInfo) GetStartedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedTime
	}
	return nil
}

func (x *UpgradeInfo) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_builtin_logical_kv_types_proto protoreflect.FileDescriptor

const file_builtin_logical_kv_types_proto_rawDesc = "" +
	"\n" +
	"\x1ebuiltin/logical/kv/types.proto\x12\x02kv\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xd7\x01\n" +
	"\rConfiguration\x12!\n" +
	"\fmax_versions\x18\x01 \x01(\rR\vmaxVersions\x12!\n" +
	"\fcas_required\x18\x02 \x01(\bR\vcasRequired\x12K\n" +
	"\x14delete_version_after\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x12deleteVersionAfter\x123\n" +
	"\x15metadata_cas_required\x18\x90\x03 \x01(\bR\x13metadataCasRequired\"\xaf\x01\n" +
	"\x0fVersionMetadata\x12=\n" +
	"\fcreated_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime\x12?\n" +
	"\rdeletion_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fdeletionTime\x12\x1c\n" +
	"\tdestroyed\x18\x03 \x01(\bR\tdestroyed\"\x8e\x06\n" +
	"\vKeyMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\bversions\x18\x02 \x03(\v2\x1d.kv.KeyMetadata.VersionsEntryR\bversions\x12'\n" +
	"\x0fcurrent_version\x18\x03 \x01(\x04R\x0ecurrentVersion\x12%\n" +
	"\x0eoldest_version\x18\x04 \x01(\x04R\roldestVersion\x12=\n" +
	"\fcreated_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime\x12=\n" +
	"\fupdated_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vupdatedTime\x12!\n" +
	"\fmax_versions\x18\a \x01(\rR\vmaxVersions\x12!\n" +
	"\fcas_required\x18\b \x01(\bR\vcasRequired\x12K\n" +
	"\x14delete_version_after\x18\t \x01(\v2\x19.google.protobuf.DurationR\x12deleteVersionAfter\x12L\n" +
	"\x0fcustom_metadata\x18\n" +
	" \x03(\v2#.kv.KeyMetadata.CustomMetadataEntryR\x0ecustomMetadata\x123\n" +
	"\x15metadata_cas_required\x18\x90\x03 \x01(\bR\x13metadataCasRequired\x129\n" +
	"\x18current_metadata_version\x18\x91\x03 \x01(\x04R\x16currentMetadataVersion\x1aP\n" +
	"\rVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.kv.VersionMetadataR\x05value:\x028\x01\x1aA\n" +
	"\x13CustomMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\aVersion\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12=\n" +
	"\fcreated_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime\x12?\n" +
	"\rdeletion_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fdeletionTime\"`\n" +
	"\vUpgradeInfo\x12=\n" +
	"\fstarted_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vstartedTime\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04doneB/Z-github.com/openbao/openbao/builtin/logical/kvb\x06proto3"

var (
	file_builtin_logical_kv_types_proto_rawDescOnce sync.Once
	file_builtin_logical_kv_types_proto_rawDescData []byte
)

func file_builtin_logical_kv_types_proto_rawDescGZIP() []byte {
	file_builtin_logical_kv_types_proto_rawDescOnce.Do(func() {
		file_builtin_logical_kv_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_builtin_logical_kv_types_proto_rawDesc), len(file_builtin_logical_kv_types_proto_rawDesc)))
	})
	return file_builtin_logical_kv_types_proto_rawDescData
}

var file_builtin_logical_kv_types_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_builtin_logical_kv_types_proto_goTypes = []any{
	(*Configuration)(nil),         // 0: kv.Configuration
	(*VersionMetadata)(nil),       // 1: kv.VersionMetadata
	(*KeyMetadata)(nil),           // 2: kv.KeyMetadata
	(*Version)(nil),               // 3: kv.Version
	(*UpgradeInfo)(nil),           // 4: kv.UpgradeInfo
	nil,                           // 5: kv.KeyMetadata.VersionsEntry
	nil,                           // 6: kv.KeyMetadata.CustomMetadataEntry
	(*durationpb.Duration)(nil),   // 7: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_builtin_logical_kv_types_proto_depIdxs = []int32{
	7,  // 0: kv.Configuration.delete_version_after:type_name -> google.protobuf.Duration
	8,  // 1: kv.VersionMetadata.created_time:type_name -> google.protobuf.Timestamp
	8,  // 2: kv.VersionMetadata.deletion_time:type_name -> google.protobuf.Timestamp
	5,  // 3: kv.KeyMetadata.versions:type_name -> kv.KeyMetadata.VersionsEntry
	8,  // 4: kv.KeyMetadata.created_time:type_name -> google.protobuf.Timestamp
	8,  // 5: kv.KeyMetadata.updated_time:type_name -> google.protobuf.Timestamp
	7,  // 6: kv.KeyMetadata.delete_version_after:type_name -> google.protobuf.Duration
	6,  // 7: kv.KeyMetadata.custom_metadata:type_name -> kv.KeyMetadata.CustomMetadataEntry
	8,  // 8: kv.Version.created_time:type_name -> google.protobuf.Timestamp
	8,  // 9: kv.Version.deletion_time:type_name -> google.protobuf.Timestamp
	8,  // 10: kv.UpgradeInfo.started_time:type_name -> google.protobuf.Timestamp
	1,  // 11: kv.KeyMetadata.VersionsEntry.value:type_name -> kv.VersionMetadata
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_builtin_logical_kv_types_proto_init() }
func file_builtin_logical_kv_types_proto_init() {
	if File_builtin_logical_kv_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_builtin_logical_kv_types_proto_rawDesc), len(file_builtin_logical_kv_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_builtin_logical_kv_types_proto_goTypes,
		DependencyIndexes: file_builtin_logical_kv_types_proto_depIdxs,
		MessageInfos:      file_builtin_logical_kv_types_proto_msgTypes,
	}.Build()
	File_builtin_logical_kv_types_proto = out.File
	file_builtin_logical_kv_types_proto_goTypes = nil
	file_builtin_logical_kv_types_proto_depIdxs = nil
}
