services:
  openbao:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    command: >
      server
      -config=/bao/config/config.hcl

    volumes:
      - openbao-data:/bao/data
      - openbao-config:/bao/config

    ports:
      - "8200"

    environment:
      BAO_ADDR: "http://0.0.0.0:8200"

    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  openbao-data:
