services:
  openbao:
    build:
      context: .
      dockerfile: Dockerfile

    command:
      - server
      - -config=/bao/config/config.hcl

    restart: unless-stopped

    volumes:
      - openbao-data:/bao/data
      - ./deploy/config.hcl:/bao/config/config.hcl:ro

    networks:
      - dokploy-network

    ports:
      - "8200"

networks:
  dokploy-network:
    external: true

volumes:
  openbao-data:
