// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: internal/vault/forwarding/request_forwarding_service.proto

package forwarding

import (
	context "context"
	forwarding "github.com/openbao/openbao/v2/internal/helper/forwarding"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequestForwarding_Echo_FullMethodName                   = "/forwarding.RequestForwarding/Echo"
	RequestForwarding_ForwardRequest_FullMethodName         = "/forwarding.RequestForwarding/ForwardRequest"
	RequestForwarding_AdvertiseNamespaceKeys_FullMethodName = "/forwarding.RequestForwarding/AdvertiseNamespaceKeys"
	RequestForwarding_SendNamespaceKeys_FullMethodName      = "/forwarding.RequestForwarding/SendNamespaceKeys"
	RequestForwarding_GetNamespaceKeys_FullMethodName       = "/forwarding.RequestForwarding/GetNamespaceKeys"
	RequestForwarding_StartInvalidations_FullMethodName     = "/forwarding.RequestForwarding/StartInvalidations"
	RequestForwarding_CheckInvalidations_FullMethodName     = "/forwarding.RequestForwarding/CheckInvalidations"
)

// RequestForwardingClient is the client API for RequestForwarding service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RequestForwarding service is always a standby->active RPC invocation. While
// named for legacy reasons (renaming a service is a breaking change), this
// service handles more than just pure request forwarding.
//
// See also: https://medium.com/@hoangxuantoank13/grpc-non-breaking-changes-breaking-changes-and-versioning-solution-1dcb989beb16
type RequestForwardingClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoReply, error)
	ForwardRequest(ctx context.Context, in *forwarding.Request, opts ...grpc.CallOption) (*forwarding.Response, error)
	// standby->active key sharing; used when the standby has knowledge of
	// namespace keys that a new active node does not. This is a two-step
	// process to avoid sending keys which the active node already knows
	// about over the wire.
	AdvertiseNamespaceKeys(ctx context.Context, in *AdvertiseNamespaceKeysRequest, opts ...grpc.CallOption) (*AdvertiseNamespaceKeysReply, error)
	SendNamespaceKeys(ctx context.Context, in *SendNamespaceKeysRequest, opts ...grpc.CallOption) (*SendNamespaceKeysReply, error)
	// active->standby key sharing; used by the standby to refresh keys.
	GetNamespaceKeys(ctx context.Context, in *GetNamespaceKeysRequest, opts ...grpc.CallOption) (*GetNamespaceKeysReply, error)
	// GRPC-backed invalidation
	StartInvalidations(ctx context.Context, in *StartInvalidationRequest, opts ...grpc.CallOption) (*StartInvalidationResponse, error)
	CheckInvalidations(ctx context.Context, in *CheckInvalidationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CheckInvalidationResponse], error)
}

type requestForwardingClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestForwardingClient(cc grpc.ClientConnInterface) RequestForwardingClient {
	return &requestForwardingClient{cc}
}

func (c *requestForwardingClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoReply)
	err := c.cc.Invoke(ctx, RequestForwarding_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestForwardingClient) ForwardRequest(ctx context.Context, in *forwarding.Request, opts ...grpc.CallOption) (*forwarding.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(forwarding.Response)
	err := c.cc.Invoke(ctx, RequestForwarding_ForwardRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestForwardingClient) AdvertiseNamespaceKeys(ctx context.Context, in *AdvertiseNamespaceKeysRequest, opts ...grpc.CallOption) (*AdvertiseNamespaceKeysReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdvertiseNamespaceKeysReply)
	err := c.cc.Invoke(ctx, RequestForwarding_AdvertiseNamespaceKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestForwardingClient) SendNamespaceKeys(ctx context.Context, in *SendNamespaceKeysRequest, opts ...grpc.CallOption) (*SendNamespaceKeysReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNamespaceKeysReply)
	err := c.cc.Invoke(ctx, RequestForwarding_SendNamespaceKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestForwardingClient) GetNamespaceKeys(ctx context.Context, in *GetNamespaceKeysRequest, opts ...grpc.CallOption) (*GetNamespaceKeysReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNamespaceKeysReply)
	err := c.cc.Invoke(ctx, RequestForwarding_GetNamespaceKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestForwardingClient) StartInvalidations(ctx context.Context, in *StartInvalidationRequest, opts ...grpc.CallOption) (*StartInvalidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInvalidationResponse)
	err := c.cc.Invoke(ctx, RequestForwarding_StartInvalidations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestForwardingClient) CheckInvalidations(ctx context.Context, in *CheckInvalidationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CheckInvalidationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RequestForwarding_ServiceDesc.Streams[0], RequestForwarding_CheckInvalidations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CheckInvalidationRequest, CheckInvalidationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RequestForwarding_CheckInvalidationsClient = grpc.ServerStreamingClient[CheckInvalidationResponse]

// RequestForwardingServer is the server API for RequestForwarding service.
// All implementations must embed UnimplementedRequestForwardingServer
// for forward compatibility.
//
// RequestForwarding service is always a standby->active RPC invocation. While
// named for legacy reasons (renaming a service is a breaking change), this
// service handles more than just pure request forwarding.
//
// See also: https://medium.com/@hoangxuantoank13/grpc-non-breaking-changes-breaking-changes-and-versioning-solution-1dcb989beb16
type RequestForwardingServer interface {
	Echo(context.Context, *EchoRequest) (*EchoReply, error)
	ForwardRequest(context.Context, *forwarding.Request) (*forwarding.Response, error)
	// standby->active key sharing; used when the standby has knowledge of
	// namespace keys that a new active node does not. This is a two-step
	// process to avoid sending keys which the active node already knows
	// about over the wire.
	AdvertiseNamespaceKeys(context.Context, *AdvertiseNamespaceKeysRequest) (*AdvertiseNamespaceKeysReply, error)
	SendNamespaceKeys(context.Context, *SendNamespaceKeysRequest) (*SendNamespaceKeysReply, error)
	// active->standby key sharing; used by the standby to refresh keys.
	GetNamespaceKeys(context.Context, *GetNamespaceKeysRequest) (*GetNamespaceKeysReply, error)
	// GRPC-backed invalidation
	StartInvalidations(context.Context, *StartInvalidationRequest) (*StartInvalidationResponse, error)
	CheckInvalidations(*CheckInvalidationRequest, grpc.ServerStreamingServer[CheckInvalidationResponse]) error
	mustEmbedUnimplementedRequestForwardingServer()
}

// UnimplementedRequestForwardingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequestForwardingServer struct{}

func (UnimplementedRequestForwardingServer) Echo(context.Context, *EchoRequest) (*EchoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedRequestForwardingServer) ForwardRequest(context.Context, *forwarding.Request) (*forwarding.Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardRequest not implemented")
}
func (UnimplementedRequestForwardingServer) AdvertiseNamespaceKeys(context.Context, *AdvertiseNamespaceKeysRequest) (*AdvertiseNamespaceKeysReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvertiseNamespaceKeys not implemented")
}
func (UnimplementedRequestForwardingServer) SendNamespaceKeys(context.Context, *SendNamespaceKeysRequest) (*SendNamespaceKeysReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNamespaceKeys not implemented")
}
func (UnimplementedRequestForwardingServer) GetNamespaceKeys(context.Context, *GetNamespaceKeysRequest) (*GetNamespaceKeysReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNamespaceKeys not implemented")
}
func (UnimplementedRequestForwardingServer) StartInvalidations(context.Context, *StartInvalidationRequest) (*StartInvalidationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInvalidations not implemented")
}
func (UnimplementedRequestForwardingServer) CheckInvalidations(*CheckInvalidationRequest, grpc.ServerStreamingServer[CheckInvalidationResponse]) error {
	return status.Error(codes.Unimplemented, "method CheckInvalidations not implemented")
}
func (UnimplementedRequestForwardingServer) mustEmbedUnimplementedRequestForwardingServer() {}
func (UnimplementedRequestForwardingServer) testEmbeddedByValue()                           {}

// UnsafeRequestForwardingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestForwardingServer will
// result in compilation errors.
type UnsafeRequestForwardingServer interface {
	mustEmbedUnimplementedRequestForwardingServer()
}

func RegisterRequestForwardingServer(s grpc.ServiceRegistrar, srv RequestForwardingServer) {
	// If the following call panics, it indicates UnimplementedRequestForwardingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequestForwarding_ServiceDesc, srv)
}

func _RequestForwarding_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestForwardingServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestForwarding_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestForwardingServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestForwarding_ForwardRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(forwarding.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestForwardingServer).ForwardRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestForwarding_ForwardRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestForwardingServer).ForwardRequest(ctx, req.(*forwarding.Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestForwarding_AdvertiseNamespaceKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvertiseNamespaceKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestForwardingServer).AdvertiseNamespaceKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestForwarding_AdvertiseNamespaceKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestForwardingServer).AdvertiseNamespaceKeys(ctx, req.(*AdvertiseNamespaceKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestForwarding_SendNamespaceKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNamespaceKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestForwardingServer).SendNamespaceKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestForwarding_SendNamespaceKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestForwardingServer).SendNamespaceKeys(ctx, req.(*SendNamespaceKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestForwarding_GetNamespaceKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamespaceKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestForwardingServer).GetNamespaceKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestForwarding_GetNamespaceKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestForwardingServer).GetNamespaceKeys(ctx, req.(*GetNamespaceKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestForwarding_StartInvalidations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInvalidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestForwardingServer).StartInvalidations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestForwarding_StartInvalidations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestForwardingServer).StartInvalidations(ctx, req.(*StartInvalidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestForwarding_CheckInvalidations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CheckInvalidationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RequestForwardingServer).CheckInvalidations(m, &grpc.GenericServerStream[CheckInvalidationRequest, CheckInvalidationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RequestForwarding_CheckInvalidationsServer = grpc.ServerStreamingServer[CheckInvalidationResponse]

// RequestForwarding_ServiceDesc is the grpc.ServiceDesc for RequestForwarding service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestForwarding_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forwarding.RequestForwarding",
	HandlerType: (*RequestForwardingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _RequestForwarding_Echo_Handler,
		},
		{
			MethodName: "ForwardRequest",
			Handler:    _RequestForwarding_ForwardRequest_Handler,
		},
		{
			MethodName: "AdvertiseNamespaceKeys",
			Handler:    _RequestForwarding_AdvertiseNamespaceKeys_Handler,
		},
		{
			MethodName: "SendNamespaceKeys",
			Handler:    _RequestForwarding_SendNamespaceKeys_Handler,
		},
		{
			MethodName: "GetNamespaceKeys",
			Handler:    _RequestForwarding_GetNamespaceKeys_Handler,
		},
		{
			MethodName: "StartInvalidations",
			Handler:    _RequestForwarding_StartInvalidations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckInvalidations",
			Handler:       _RequestForwarding_CheckInvalidations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/vault/forwarding/request_forwarding_service.proto",
}
