// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: vault/forwarding/request_forwarding_service.proto

package forwarding

import (
	forwarding "github.com/openbao/openbao/helper/forwarding"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// ClusterAddr is used to send up a standby node's address to the active
	// node upon heartbeat
	ClusterAddr string `protobuf:"bytes,2,opt,name=cluster_addr,json=clusterAddr,proto3" json:"cluster_addr,omitempty"`
	// ClusterAddrs is used to send up a list of cluster addresses to a dr
	// primary from a dr secondary
	ClusterAddrs        []string         `protobuf:"bytes,3,rep,name=cluster_addrs,json=clusterAddrs,proto3" json:"cluster_addrs,omitempty"`
	RaftAppliedIndex    uint64           `protobuf:"varint,4,opt,name=raft_applied_index,json=raftAppliedIndex,proto3" json:"raft_applied_index,omitempty"`
	RaftNodeID          string           `protobuf:"bytes,5,opt,name=raft_node_id,json=raftNodeId,proto3" json:"raft_node_id,omitempty"`
	NodeInfo            *NodeInformation `protobuf:"bytes,6,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	RaftTerm            uint64           `protobuf:"varint,7,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	RaftDesiredSuffrage string           `protobuf:"bytes,8,opt,name=raft_desired_suffrage,json=raftDesiredSuffrage,proto3" json:"raft_desired_suffrage,omitempty"`
	RaftUpgradeVersion  string           `protobuf:"bytes,9,opt,name=raft_upgrade_version,json=raftUpgradeVersion,proto3" json:"raft_upgrade_version,omitempty"`
	SdkVersion          string           `protobuf:"bytes,11,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoRequest) GetClusterAddr() string {
	if x != nil {
		return x.ClusterAddr
	}
	return ""
}

func (x *EchoRequest) GetClusterAddrs() []string {
	if x != nil {
		return x.ClusterAddrs
	}
	return nil
}

func (x *EchoRequest) GetRaftAppliedIndex() uint64 {
	if x != nil {
		return x.RaftAppliedIndex
	}
	return 0
}

func (x *EchoRequest) GetRaftNodeID() string {
	if x != nil {
		return x.RaftNodeID
	}
	return ""
}

func (x *EchoRequest) GetNodeInfo() *NodeInformation {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *EchoRequest) GetRaftTerm() uint64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

func (x *EchoRequest) GetRaftDesiredSuffrage() string {
	if x != nil {
		return x.RaftDesiredSuffrage
	}
	return ""
}

func (x *EchoRequest) GetRaftUpgradeVersion() string {
	if x != nil {
		return x.RaftUpgradeVersion
	}
	return ""
}

func (x *EchoRequest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

type EchoReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Message          string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ClusterAddrs     []string               `protobuf:"bytes,2,rep,name=cluster_addrs,json=clusterAddrs,proto3" json:"cluster_addrs,omitempty"`
	ReplicationState uint32                 `protobuf:"varint,3,opt,name=replication_state,json=replicationState,proto3" json:"replication_state,omitempty"`
	RaftAppliedIndex uint64                 `protobuf:"varint,4,opt,name=raft_applied_index,json=raftAppliedIndex,proto3" json:"raft_applied_index,omitempty"`
	RaftNodeID       string                 `protobuf:"bytes,5,opt,name=raft_node_id,json=raftNodeId,proto3" json:"raft_node_id,omitempty"`
	NodeInfo         *NodeInformation       `protobuf:"bytes,6,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EchoReply) Reset() {
	*x = EchoReply{}
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoReply) ProtoMessage() {}

func (x *EchoReply) ProtoReflect() protoreflect.Message {
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoReply.ProtoReflect.Descriptor instead.
func (*EchoReply) Descriptor() ([]byte, []int) {
	return file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP(), []int{1}
}

func (x *EchoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoReply) GetClusterAddrs() []string {
	if x != nil {
		return x.ClusterAddrs
	}
	return nil
}

func (x *EchoReply) GetReplicationState() uint32 {
	if x != nil {
		return x.ReplicationState
	}
	return 0
}

func (x *EchoReply) GetRaftAppliedIndex() uint64 {
	if x != nil {
		return x.RaftAppliedIndex
	}
	return 0
}

func (x *EchoReply) GetRaftNodeID() string {
	if x != nil {
		return x.RaftNodeID
	}
	return ""
}

func (x *EchoReply) GetNodeInfo() *NodeInformation {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

type NodeInformation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClusterAddr      string                 `protobuf:"bytes,1,opt,name=cluster_addr,json=clusterAddr,proto3" json:"cluster_addr,omitempty"`
	ApiAddr          string                 `protobuf:"bytes,2,opt,name=api_addr,json=apiAddr,proto3" json:"api_addr,omitempty"`
	Mode             string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	NodeID           string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ReplicationState uint32                 `protobuf:"varint,5,opt,name=replication_state,json=replicationState,proto3" json:"replication_state,omitempty"`
	Hostname         string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeInformation) Reset() {
	*x = NodeInformation{}
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInformation) ProtoMessage() {}

func (x *NodeInformation) ProtoReflect() protoreflect.Message {
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInformation.ProtoReflect.Descriptor instead.
func (*NodeInformation) Descriptor() ([]byte, []int) {
	return file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInformation) GetClusterAddr() string {
	if x != nil {
		return x.ClusterAddr
	}
	return ""
}

func (x *NodeInformation) GetApiAddr() string {
	if x != nil {
		return x.ApiAddr
	}
	return ""
}

func (x *NodeInformation) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *NodeInformation) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *NodeInformation) GetReplicationState() uint32 {
	if x != nil {
		return x.ReplicationState
	}
	return 0
}

func (x *NodeInformation) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ClientKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	X             []byte                 `protobuf:"bytes,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             []byte                 `protobuf:"bytes,3,opt,name=y,proto3" json:"y,omitempty"`
	D             []byte                 `protobuf:"bytes,4,opt,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientKey) Reset() {
	*x = ClientKey{}
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientKey) ProtoMessage() {}

func (x *ClientKey) ProtoReflect() protoreflect.Message {
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientKey.ProtoReflect.Descriptor instead.
func (*ClientKey) Descriptor() ([]byte, []int) {
	return file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP(), []int{3}
}

func (x *ClientKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClientKey) GetX() []byte {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *ClientKey) GetY() []byte {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *ClientKey) GetD() []byte {
	if x != nil {
		return x.D
	}
	return nil
}

type NamespaceKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceKey) Reset() {
	*x = NamespaceKey{}
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceKey) ProtoMessage() {}

func (x *NamespaceKey) ProtoReflect() protoreflect.Message {
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceKey.ProtoReflect.Descriptor instead.
func (*NamespaceKey) Descriptor() ([]byte, []int) {
	return file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP(), []int{4}
}

func (x *NamespaceKey) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NamespaceKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type AdvertiseNamespaceKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertiseNamespaceKeysRequest) Reset() {
	*x = AdvertiseNamespaceKeysRequest{}
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertiseNamespaceKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertiseNamespaceKeysRequest) ProtoMessage() {}

func (x *AdvertiseNamespaceKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertiseNamespaceKeysRequest.ProtoReflect.Descriptor instead.
func (*AdvertiseNamespaceKeysRequest) Descriptor() ([]byte, []int) {
	return file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP(), []int{5}
}

func (x *AdvertiseNamespaceKeysRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type AdvertiseNamespaceKeysReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Retry         bool                   `protobuf:"varint,2,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertiseNamespaceKeysReply) Reset() {
	*x = AdvertiseNamespaceKeysReply{}
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertiseNamespaceKeysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertiseNamespaceKeysReply) ProtoMessage() {}

func (x *AdvertiseNamespaceKeysReply) ProtoReflect() protoreflect.Message {
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertiseNamespaceKeysReply.ProtoReflect.Descriptor instead.
func (*AdvertiseNamespaceKeysReply) Descriptor() ([]byte, []int) {
	return file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP(), []int{6}
}

func (x *AdvertiseNamespaceKeysReply) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *AdvertiseNamespaceKeysReply) GetRetry() bool {
	if x != nil {
		return x.Retry
	}
	return false
}

type SendNamespaceKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*NamespaceKey        `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNamespaceKeysRequest) Reset() {
	*x = SendNamespaceKeysRequest{}
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNamespaceKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNamespaceKeysRequest) ProtoMessage() {}

func (x *SendNamespaceKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNamespaceKeysRequest.ProtoReflect.Descriptor instead.
func (*SendNamespaceKeysRequest) Descriptor() ([]byte, []int) {
	return file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP(), []int{7}
}

func (x *SendNamespaceKeysRequest) GetKeys() []*NamespaceKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SendNamespaceKeysReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Retry         bool                   `protobuf:"varint,1,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNamespaceKeysReply) Reset() {
	*x = SendNamespaceKeysReply{}
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNamespaceKeysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNamespaceKeysReply) ProtoMessage() {}

func (x *SendNamespaceKeysReply) ProtoReflect() protoreflect.Message {
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNamespaceKeysReply.ProtoReflect.Descriptor instead.
func (*SendNamespaceKeysReply) Descriptor() ([]byte, []int) {
	return file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP(), []int{8}
}

func (x *SendNamespaceKeysReply) GetRetry() bool {
	if x != nil {
		return x.Retry
	}
	return false
}

type GetNamespaceKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceKeysRequest) Reset() {
	*x = GetNamespaceKeysRequest{}
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceKeysRequest) ProtoMessage() {}

func (x *GetNamespaceKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceKeysRequest.ProtoReflect.Descriptor instead.
func (*GetNamespaceKeysRequest) Descriptor() ([]byte, []int) {
	return file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetNamespaceKeysRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type GetNamespaceKeysReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*NamespaceKey        `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceKeysReply) Reset() {
	*x = GetNamespaceKeysReply{}
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceKeysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceKeysReply) ProtoMessage() {}

func (x *GetNamespaceKeysReply) ProtoReflect() protoreflect.Message {
	mi := &file_vault_forwarding_request_forwarding_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceKeysReply.ProtoReflect.Descriptor instead.
func (*GetNamespaceKeysReply) Descriptor() ([]byte, []int) {
	return file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetNamespaceKeysReply) GetKeys() []*NamespaceKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_vault_forwarding_request_forwarding_service_proto protoreflect.FileDescriptor

const file_vault_forwarding_request_forwarding_service_proto_rawDesc = "" +
	"\n" +
	"1vault/forwarding/request_forwarding_service.proto\x12\n" +
	"forwarding\x1a\x1dhelper/forwarding/types.proto\"\x9d\x03\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\fcluster_addr\x18\x02 \x01(\tR\vclusterAddr\x12#\n" +
	"\rcluster_addrs\x18\x03 \x03(\tR\fclusterAddrs\x12,\n" +
	"\x12raft_applied_index\x18\x04 \x01(\x04R\x10raftAppliedIndex\x12 \n" +
	"\fraft_node_id\x18\x05 \x01(\tR\n" +
	"raftNodeID\x128\n" +
	"\tnode_info\x18\x06 \x01(\v2\x1b.forwarding.NodeInformationR\bnodeInfo\x12\x1b\n" +
	"\traft_term\x18\a \x01(\x04R\braftTerm\x122\n" +
	"\x15raft_desired_suffrage\x18\b \x01(\tR\x13raftDesiredSuffrage\x120\n" +
	"\x14raft_upgrade_version\x18\t \x01(\tR\x12raftUpgradeVersion\x12\x1f\n" +
	"\vsdk_version\x18\v \x01(\tR\n" +
	"sdkVersion\"\x81\x02\n" +
	"\tEchoReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\rcluster_addrs\x18\x02 \x03(\tR\fclusterAddrs\x12+\n" +
	"\x11replication_state\x18\x03 \x01(\rR\x10replicationState\x12,\n" +
	"\x12raft_applied_index\x18\x04 \x01(\x04R\x10raftAppliedIndex\x12 \n" +
	"\fraft_node_id\x18\x05 \x01(\tR\n" +
	"raftNodeID\x128\n" +
	"\tnode_info\x18\x06 \x01(\v2\x1b.forwarding.NodeInformationR\bnodeInfo\"\xc5\x01\n" +
	"\x0fNodeInformation\x12!\n" +
	"\fcluster_addr\x18\x01 \x01(\tR\vclusterAddr\x12\x19\n" +
	"\bapi_addr\x18\x02 \x01(\tR\aapiAddr\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeID\x12+\n" +
	"\x11replication_state\x18\x05 \x01(\rR\x10replicationState\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\"I\n" +
	"\tClientKey\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\f\n" +
	"\x01x\x18\x02 \x01(\fR\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\fR\x01y\x12\f\n" +
	"\x01d\x18\x04 \x01(\fR\x01d\"4\n" +
	"\fNamespaceKey\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"?\n" +
	"\x1dAdvertiseNamespaceKeysRequest\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\"S\n" +
	"\x1bAdvertiseNamespaceKeysReply\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12\x14\n" +
	"\x05retry\x18\x02 \x01(\bR\x05retry\"H\n" +
	"\x18SendNamespaceKeysRequest\x12,\n" +
	"\x04keys\x18\x01 \x03(\v2\x18.forwarding.NamespaceKeyR\x04keys\".\n" +
	"\x16SendNamespaceKeysReply\x12\x14\n" +
	"\x05retry\x18\x01 \x01(\bR\x05retry\"9\n" +
	"\x17GetNamespaceKeysRequest\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\"E\n" +
	"\x15GetNamespaceKeysReply\x12,\n" +
	"\x04keys\x18\x01 \x03(\v2\x18.forwarding.NamespaceKeyR\x04keys2\xbb\x03\n" +
	"\x11RequestForwarding\x12=\n" +
	"\x0eForwardRequest\x12\x13.forwarding.Request\x1a\x14.forwarding.Response\"\x00\x128\n" +
	"\x04Echo\x12\x17.forwarding.EchoRequest\x1a\x15.forwarding.EchoReply\"\x00\x12n\n" +
	"\x16AdvertiseNamespaceKeys\x12).forwarding.AdvertiseNamespaceKeysRequest\x1a'.forwarding.AdvertiseNamespaceKeysReply\"\x00\x12_\n" +
	"\x11SendNamespaceKeys\x12$.forwarding.SendNamespaceKeysRequest\x1a\".forwarding.SendNamespaceKeysReply\"\x00\x12\\\n" +
	"\x10GetNamespaceKeys\x12#.forwarding.GetNamespaceKeysRequest\x1a!.forwarding.GetNamespaceKeysReply\"\x00B-Z+github.com/openbao/openbao/vault/forwardingb\x06proto3"

var (
	file_vault_forwarding_request_forwarding_service_proto_rawDescOnce sync.Once
	file_vault_forwarding_request_forwarding_service_proto_rawDescData []byte
)

func file_vault_forwarding_request_forwarding_service_proto_rawDescGZIP() []byte {
	file_vault_forwarding_request_forwarding_service_proto_rawDescOnce.Do(func() {
		file_vault_forwarding_request_forwarding_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_forwarding_request_forwarding_service_proto_rawDesc), len(file_vault_forwarding_request_forwarding_service_proto_rawDesc)))
	})
	return file_vault_forwarding_request_forwarding_service_proto_rawDescData
}

var file_vault_forwarding_request_forwarding_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_vault_forwarding_request_forwarding_service_proto_goTypes = []any{
	(*EchoRequest)(nil),                   // 0: forwarding.EchoRequest
	(*EchoReply)(nil),                     // 1: forwarding.EchoReply
	(*NodeInformation)(nil),               // 2: forwarding.NodeInformation
	(*ClientKey)(nil),                     // 3: forwarding.ClientKey
	(*NamespaceKey)(nil),                  // 4: forwarding.NamespaceKey
	(*AdvertiseNamespaceKeysRequest)(nil), // 5: forwarding.AdvertiseNamespaceKeysRequest
	(*AdvertiseNamespaceKeysReply)(nil),   // 6: forwarding.AdvertiseNamespaceKeysReply
	(*SendNamespaceKeysRequest)(nil),      // 7: forwarding.SendNamespaceKeysRequest
	(*SendNamespaceKeysReply)(nil),        // 8: forwarding.SendNamespaceKeysReply
	(*GetNamespaceKeysRequest)(nil),       // 9: forwarding.GetNamespaceKeysRequest
	(*GetNamespaceKeysReply)(nil),         // 10: forwarding.GetNamespaceKeysReply
	(*forwarding.Request)(nil),            // 11: forwarding.Request
	(*forwarding.Response)(nil),           // 12: forwarding.Response
}
var file_vault_forwarding_request_forwarding_service_proto_depIDxs = []int32{
	2,  // 0: forwarding.EchoRequest.node_info:type_name -> forwarding.NodeInformation
	2,  // 1: forwarding.EchoReply.node_info:type_name -> forwarding.NodeInformation
	4,  // 2: forwarding.SendNamespaceKeysRequest.keys:type_name -> forwarding.NamespaceKey
	4,  // 3: forwarding.GetNamespaceKeysReply.keys:type_name -> forwarding.NamespaceKey
	11, // 4: forwarding.RequestForwarding.ForwardRequest:input_type -> forwarding.Request
	0,  // 5: forwarding.RequestForwarding.Echo:input_type -> forwarding.EchoRequest
	5,  // 6: forwarding.RequestForwarding.AdvertiseNamespaceKeys:input_type -> forwarding.AdvertiseNamespaceKeysRequest
	7,  // 7: forwarding.RequestForwarding.SendNamespaceKeys:input_type -> forwarding.SendNamespaceKeysRequest
	9,  // 8: forwarding.RequestForwarding.GetNamespaceKeys:input_type -> forwarding.GetNamespaceKeysRequest
	12, // 9: forwarding.RequestForwarding.ForwardRequest:output_type -> forwarding.Response
	1,  // 10: forwarding.RequestForwarding.Echo:output_type -> forwarding.EchoReply
	6,  // 11: forwarding.RequestForwarding.AdvertiseNamespaceKeys:output_type -> forwarding.AdvertiseNamespaceKeysReply
	8,  // 12: forwarding.RequestForwarding.SendNamespaceKeys:output_type -> forwarding.SendNamespaceKeysReply
	10, // 13: forwarding.RequestForwarding.GetNamespaceKeys:output_type -> forwarding.GetNamespaceKeysReply
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_vault_forwarding_request_forwarding_service_proto_init() }
func file_vault_forwarding_request_forwarding_service_proto_init() {
	if File_vault_forwarding_request_forwarding_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_forwarding_request_forwarding_service_proto_rawDesc), len(file_vault_forwarding_request_forwarding_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_forwarding_request_forwarding_service_proto_goTypes,
		DependencyIndexes: file_vault_forwarding_request_forwarding_service_proto_depIDxs,
		MessageInfos:      file_vault_forwarding_request_forwarding_service_proto_msgTypes,
	}.Build()
	File_vault_forwarding_request_forwarding_service_proto = out.File
	file_vault_forwarding_request_forwarding_service_proto_goTypes = nil
	file_vault_forwarding_request_forwarding_service_proto_depIDxs = nil
}
