# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

contact_links:
  - name: Ask a question
    url: https://lists.openssf.org/g/openbao
    about: For increased visibility, please send questions to our mailing list
