name: Tests

on: [push, workflow_dispatch]

jobs:
  fmtcheck:
    runs-on: ubuntu-latest
    env:
      GOFUMPT_VERSION: 0.3.1
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: .go-version
      - run: |
          go install "mvdan.cc/gofumpt@v${GOFUMPT_VERSION}"
          make fmtcheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: .go-version
      - run: make test

  integrationTest:
    runs-on: ubuntu-latest
    needs: [fmtcheck, test]
    strategy:
      fail-fast: false
      matrix:
        kind-k8s-version: [1.24.15, 1.25.11, 1.26.6, 1.27.3, 1.28.0]
        enterprise: ["", "-ent"]
    name: Integration test ${{ matrix.enterprise }} kind ${{ matrix.kind-k8s-version }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          version: v0.20.0
          cluster_name: vault-plugin-secrets-kubernetes
          config: integrationtest/kind/config.yaml
          node_image: kindest/node:v${{ matrix.kind-k8s-version }}
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: .go-version
      - env:
          VAULT_LICENSE_CI: ${{ secrets.VAULT_LICENSE_CI }}
        run: make setup-integration-test${{ matrix.enterprise }}
      - env:
          INTEGRATION_TESTS: true
        run: make integration-test TESTARGS="-v"
