// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: sdk/logical/plugin.proto

package logical

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginEnvironment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VaultVersion is the version of the Vault server
	VaultVersion string `protobuf:"bytes,1,opt,name=vault_version,json=vaultVersion,proto3" json:"vault_version,omitempty"`
	// VaultVersionPrerelease is the prerelease information of the Vault server
	VaultVersionPrerelease string `protobuf:"bytes,2,opt,name=vault_version_prerelease,json=vaultVersionPrerelease,proto3" json:"vault_version_prerelease,omitempty"`
	// VaultVersionMetadata is the version metadata of the Vault server
	VaultVersionMetadata string `protobuf:"bytes,3,opt,name=vault_version_metadata,json=vaultVersionMetadata,proto3" json:"vault_version_metadata,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PluginEnvironment) Reset() {
	*x = PluginEnvironment{}
	mi := &file_sdk_logical_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEnvironment) ProtoMessage() {}

func (x *PluginEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_logical_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEnvironment.ProtoReflect.Descriptor instead.
func (*PluginEnvironment) Descriptor() ([]byte, []int) {
	return file_sdk_logical_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginEnvironment) GetVaultVersion() string {
	if x != nil {
		return x.VaultVersion
	}
	return ""
}

func (x *PluginEnvironment) GetVaultVersionPrerelease() string {
	if x != nil {
		return x.VaultVersionPrerelease
	}
	return ""
}

func (x *PluginEnvironment) GetVaultVersionMetadata() string {
	if x != nil {
		return x.VaultVersionMetadata
	}
	return ""
}

var File_sdk_logical_plugin_proto protoreflect.FileDescriptor

const file_sdk_logical_plugin_proto_rawDesc = "" +
	"\n" +
	"\x18sdk/logical/plugin.proto\x12\alogical\"\xa8\x01\n" +
	"\x11PluginEnvironment\x12#\n" +
	"\rvault_version\x18\x01 \x01(\tR\fvaultVersion\x128\n" +
	"\x18vault_version_prerelease\x18\x02 \x01(\tR\x16vaultVersionPrerelease\x124\n" +
	"\x16vault_version_metadata\x18\x03 \x01(\tR\x14vaultVersionMetadataB+Z)github.com/openbao/openbao/sdk/v2/logicalb\x06proto3"

var (
	file_sdk_logical_plugin_proto_rawDescOnce sync.Once
	file_sdk_logical_plugin_proto_rawDescData []byte
)

func file_sdk_logical_plugin_proto_rawDescGZIP() []byte {
	file_sdk_logical_plugin_proto_rawDescOnce.Do(func() {
		file_sdk_logical_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_logical_plugin_proto_rawDesc), len(file_sdk_logical_plugin_proto_rawDesc)))
	})
	return file_sdk_logical_plugin_proto_rawDescData
}

var file_sdk_logical_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_logical_plugin_proto_goTypes = []any{
	(*PluginEnvironment)(nil), // 0: logical.PluginEnvironment
}
var file_sdk_logical_plugin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_logical_plugin_proto_init() }
func file_sdk_logical_plugin_proto_init() {
	if File_sdk_logical_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_logical_plugin_proto_rawDesc), len(file_sdk_logical_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_logical_plugin_proto_goTypes,
		DependencyIndexes: file_sdk_logical_plugin_proto_depIdxs,
		MessageInfos:      file_sdk_logical_plugin_proto_msgTypes,
	}.Build()
	File_sdk_logical_plugin_proto = out.File
	file_sdk_logical_plugin_proto_goTypes = nil
	file_sdk_logical_plugin_proto_depIdxs = nil
}
