// Copyright (c) 2025 OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: vault/namespace_seal_service.proto

package vault

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SealStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace_uuid is the UUID of the namespace
	NamespaceUuid string `protobuf:"bytes,1,opt,name=namespace_uuid,json=namespaceUuid,proto3" json:"namespace_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealStateRequest) Reset() {
	*x = SealStateRequest{}
	mi := &file_vault_namespace_seal_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealStateRequest) ProtoMessage() {}

func (x *SealStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_namespace_seal_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealStateRequest.ProtoReflect.Descriptor instead.
func (*SealStateRequest) Descriptor() ([]byte, []int) {
	return file_vault_namespace_seal_service_proto_rawDescGZIP(), []int{0}
}

func (x *SealStateRequest) GetNamespaceUuid() string {
	if x != nil {
		return x.NamespaceUuid
	}
	return ""
}

type SealStateStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace_uuid is the UUID of the namespace
	NamespaceUuid string `protobuf:"bytes,1,opt,name=namespace_uuid,json=namespaceUuid,proto3" json:"namespace_uuid,omitempty"`
	// root_key contains the namespace root key if it is unsealed.
	// It is unset otherwise.
	RootKey       []byte `protobuf:"bytes,2,opt,name=root_key,json=rootKey,proto3,oneof" json:"root_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealStateStatus) Reset() {
	*x = SealStateStatus{}
	mi := &file_vault_namespace_seal_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealStateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealStateStatus) ProtoMessage() {}

func (x *SealStateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_vault_namespace_seal_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealStateStatus.ProtoReflect.Descriptor instead.
func (*SealStateStatus) Descriptor() ([]byte, []int) {
	return file_vault_namespace_seal_service_proto_rawDescGZIP(), []int{1}
}

func (x *SealStateStatus) GetNamespaceUuid() string {
	if x != nil {
		return x.NamespaceUuid
	}
	return ""
}

func (x *SealStateStatus) GetRootKey() []byte {
	if x != nil {
		return x.RootKey
	}
	return nil
}

type SealStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SealStatus    []*SealStateStatus     `protobuf:"bytes,1,rep,name=seal_status,json=sealStatus,proto3" json:"seal_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealStateResponse) Reset() {
	*x = SealStateResponse{}
	mi := &file_vault_namespace_seal_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealStateResponse) ProtoMessage() {}

func (x *SealStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_namespace_seal_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealStateResponse.ProtoReflect.Descriptor instead.
func (*SealStateResponse) Descriptor() ([]byte, []int) {
	return file_vault_namespace_seal_service_proto_rawDescGZIP(), []int{2}
}

func (x *SealStateResponse) GetSealStatus() []*SealStateStatus {
	if x != nil {
		return x.SealStatus
	}
	return nil
}

var File_vault_namespace_seal_service_proto protoreflect.FileDescriptor

const file_vault_namespace_seal_service_proto_rawDesc = "" +
	"\n" +
	"\"vault/namespace_seal_service.proto\x12\x05vault\"9\n" +
	"\x10SealStateRequest\x12%\n" +
	"\x0enamespace_uuid\x18\x01 \x01(\tR\rnamespaceUuid\"e\n" +
	"\x0fSealStateStatus\x12%\n" +
	"\x0enamespace_uuid\x18\x01 \x01(\tR\rnamespaceUuid\x12\x1e\n" +
	"\broot_key\x18\x02 \x01(\fH\x00R\arootKey\x88\x01\x01B\v\n" +
	"\t_root_key\"L\n" +
	"\x11SealStateResponse\x127\n" +
	"\vseal_status\x18\x01 \x03(\v2\x16.vault.SealStateStatusR\n" +
	"sealStatus2]\n" +
	"\x14SealStatusForwarding\x12E\n" +
	"\x0eRequestRootKey\x12\x17.vault.SealStateRequest\x1a\x18.vault.SealStateResponse\"\x00B\"Z github.com/openbao/openbao/vaultb\x06proto3"

var (
	file_vault_namespace_seal_service_proto_rawDescOnce sync.Once
	file_vault_namespace_seal_service_proto_rawDescData []byte
)

func file_vault_namespace_seal_service_proto_rawDescGZIP() []byte {
	file_vault_namespace_seal_service_proto_rawDescOnce.Do(func() {
		file_vault_namespace_seal_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_namespace_seal_service_proto_rawDesc), len(file_vault_namespace_seal_service_proto_rawDesc)))
	})
	return file_vault_namespace_seal_service_proto_rawDescData
}

var file_vault_namespace_seal_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vault_namespace_seal_service_proto_goTypes = []any{
	(*SealStateRequest)(nil),  // 0: vault.SealStateRequest
	(*SealStateStatus)(nil),   // 1: vault.SealStateStatus
	(*SealStateResponse)(nil), // 2: vault.SealStateResponse
}
var file_vault_namespace_seal_service_proto_depIdxs = []int32{
	1, // 0: vault.SealStateResponse.seal_status:type_name -> vault.SealStateStatus
	0, // 1: vault.SealStatusForwarding.RequestRootKey:input_type -> vault.SealStateRequest
	2, // 2: vault.SealStatusForwarding.RequestRootKey:output_type -> vault.SealStateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vault_namespace_seal_service_proto_init() }
func file_vault_namespace_seal_service_proto_init() {
	if File_vault_namespace_seal_service_proto != nil {
		return
	}
	file_vault_namespace_seal_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_namespace_seal_service_proto_rawDesc), len(file_vault_namespace_seal_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_namespace_seal_service_proto_goTypes,
		DependencyIndexes: file_vault_namespace_seal_service_proto_depIdxs,
		MessageInfos:      file_vault_namespace_seal_service_proto_msgTypes,
	}.Build()
	File_vault_namespace_seal_service_proto = out.File
	file_vault_namespace_seal_service_proto_goTypes = nil
	file_vault_namespace_seal_service_proto_depIdxs = nil
}
