// Copyright (c) 2025 OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: vault/namespace_seal_service.proto

package vault

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SealStatusForwarding_RequestRootKey_FullMethodName = "/vault.SealStatusForwarding/RequestRootKey"
)

// SealStatusForwardingClient is the client API for SealStatusForwarding service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SealStatusForwardingClient interface {
	RequestRootKey(ctx context.Context, in *SealStateRequest, opts ...grpc.CallOption) (*SealStateResponse, error)
}

type sealStatusForwardingClient struct {
	cc grpc.ClientConnInterface
}

func NewSealStatusForwardingClient(cc grpc.ClientConnInterface) SealStatusForwardingClient {
	return &sealStatusForwardingClient{cc}
}

func (c *sealStatusForwardingClient) RequestRootKey(ctx context.Context, in *SealStateRequest, opts ...grpc.CallOption) (*SealStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SealStateResponse)
	err := c.cc.Invoke(ctx, SealStatusForwarding_RequestRootKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SealStatusForwardingServer is the server API for SealStatusForwarding service.
// All implementations must embed UnimplementedSealStatusForwardingServer
// for forward compatibility.
type SealStatusForwardingServer interface {
	RequestRootKey(context.Context, *SealStateRequest) (*SealStateResponse, error)
	mustEmbedUnimplementedSealStatusForwardingServer()
}

// UnimplementedSealStatusForwardingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSealStatusForwardingServer struct{}

func (UnimplementedSealStatusForwardingServer) RequestRootKey(context.Context, *SealStateRequest) (*SealStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRootKey not implemented")
}
func (UnimplementedSealStatusForwardingServer) mustEmbedUnimplementedSealStatusForwardingServer() {}
func (UnimplementedSealStatusForwardingServer) testEmbeddedByValue()                              {}

// UnsafeSealStatusForwardingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SealStatusForwardingServer will
// result in compilation errors.
type UnsafeSealStatusForwardingServer interface {
	mustEmbedUnimplementedSealStatusForwardingServer()
}

func RegisterSealStatusForwardingServer(s grpc.ServiceRegistrar, srv SealStatusForwardingServer) {
	// If the following call pancis, it indicates UnimplementedSealStatusForwardingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SealStatusForwarding_ServiceDesc, srv)
}

func _SealStatusForwarding_RequestRootKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SealStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SealStatusForwardingServer).RequestRootKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SealStatusForwarding_RequestRootKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SealStatusForwardingServer).RequestRootKey(ctx, req.(*SealStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SealStatusForwarding_ServiceDesc is the grpc.ServiceDesc for SealStatusForwarding service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SealStatusForwarding_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vault.SealStatusForwarding",
	HandlerType: (*SealStatusForwardingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestRootKey",
			Handler:    _SealStatusForwarding_RequestRootKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault/namespace_seal_service.proto",
}
