// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: sdk/joinplugin/pb/join.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_sdk_joinplugin_pb_join_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_joinplugin_pb_join_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_sdk_joinplugin_pb_join_proto_rawDescGZIP(), []int{0}
}

type CandidateArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateArgs) Reset() {
	*x = CandidateArgs{}
	mi := &file_sdk_joinplugin_pb_join_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateArgs) ProtoMessage() {}

func (x *CandidateArgs) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_joinplugin_pb_join_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateArgs.ProtoReflect.Descriptor instead.
func (*CandidateArgs) Descriptor() ([]byte, []int) {
	return file_sdk_joinplugin_pb_join_proto_rawDescGZIP(), []int{1}
}

func (x *CandidateArgs) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Scheme        string                 `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_sdk_joinplugin_pb_join_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_joinplugin_pb_join_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_sdk_joinplugin_pb_join_proto_rawDescGZIP(), []int{2}
}

func (x *Candidate) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Candidate) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Candidate) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Candidates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*Candidate           `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidates) Reset() {
	*x = Candidates{}
	mi := &file_sdk_joinplugin_pb_join_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidates) ProtoMessage() {}

func (x *Candidates) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_joinplugin_pb_join_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidates.ProtoReflect.Descriptor instead.
func (*Candidates) Descriptor() ([]byte, []int) {
	return file_sdk_joinplugin_pb_join_proto_rawDescGZIP(), []int{3}
}

func (x *Candidates) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

var File_sdk_joinplugin_pb_join_proto protoreflect.FileDescriptor

const file_sdk_joinplugin_pb_join_proto_rawDesc = "" +
	"\n" +
	"\x1csdk/joinplugin/pb/join.proto\x12\x04join\"\a\n" +
	"\x05Empty\"\x83\x01\n" +
	"\rCandidateArgs\x127\n" +
	"\x06config\x18\x01 \x03(\v2\x1f.join.CandidateArgs.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\tCandidate\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"=\n" +
	"\n" +
	"Candidates\x12/\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x0f.join.CandidateR\n" +
	"candidates2`\n" +
	"\x04Join\x123\n" +
	"\n" +
	"candidates\x12\x13.join.CandidateArgs\x1a\x10.join.Candidates\x12#\n" +
	"\acleanup\x12\v.join.Empty\x1a\v.join.EmptyB2Z0github.com/openbao/openbao/sdk/v2/plugin/join/pbb\x06proto3"

var (
	file_sdk_joinplugin_pb_join_proto_rawDescOnce sync.Once
	file_sdk_joinplugin_pb_join_proto_rawDescData []byte
)

func file_sdk_joinplugin_pb_join_proto_rawDescGZIP() []byte {
	file_sdk_joinplugin_pb_join_proto_rawDescOnce.Do(func() {
		file_sdk_joinplugin_pb_join_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_joinplugin_pb_join_proto_rawDesc), len(file_sdk_joinplugin_pb_join_proto_rawDesc)))
	})
	return file_sdk_joinplugin_pb_join_proto_rawDescData
}

var file_sdk_joinplugin_pb_join_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sdk_joinplugin_pb_join_proto_goTypes = []any{
	(*Empty)(nil),         // 0: join.Empty
	(*CandidateArgs)(nil), // 1: join.CandidateArgs
	(*Candidate)(nil),     // 2: join.Candidate
	(*Candidates)(nil),    // 3: join.Candidates
	nil,                   // 4: join.CandidateArgs.ConfigEntry
}
var file_sdk_joinplugin_pb_join_proto_depIdxs = []int32{
	4, // 0: join.CandidateArgs.config:type_name -> join.CandidateArgs.ConfigEntry
	2, // 1: join.Candidates.candidates:type_name -> join.Candidate
	1, // 2: join.Join.candidates:input_type -> join.CandidateArgs
	0, // 3: join.Join.cleanup:input_type -> join.Empty
	3, // 4: join.Join.candidates:output_type -> join.Candidates
	0, // 5: join.Join.cleanup:output_type -> join.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sdk_joinplugin_pb_join_proto_init() }
func file_sdk_joinplugin_pb_join_proto_init() {
	if File_sdk_joinplugin_pb_join_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_joinplugin_pb_join_proto_rawDesc), len(file_sdk_joinplugin_pb_join_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_joinplugin_pb_join_proto_goTypes,
		DependencyIndexes: file_sdk_joinplugin_pb_join_proto_depIdxs,
		MessageInfos:      file_sdk_joinplugin_pb_join_proto_msgTypes,
	}.Build()
	File_sdk_joinplugin_pb_join_proto = out.File
	file_sdk_joinplugin_pb_join_proto_goTypes = nil
	file_sdk_joinplugin_pb_join_proto_depIdxs = nil
}
