import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    community: [
        "index",
        {
            type: 'link',
            label: 'GitHub Discussions',
            href: "https://github.com/openbao/openbao/discussions",
        },
        {
            type: 'link',
            label: 'Zulip Chat Server',
            href: "https://linuxfoundation.zulipchat.com/",
        },
        {
            "Release Notes": [{
                type: 'autogenerated',
                dirName: 'release-notes',
            }],
            "Deprecation Notices": [{
                type: 'autogenerated',
                dirName: 'deprecation',
            }],
        },
        "known-issues",
        {
            Contributing: [{
                type: 'autogenerated',
                dirName: 'contributing',
            }],
            Policies: [{
                type: 'autogenerated',
                dirName: 'policies',
            }],
            RFCs: [{
                type: 'autogenerated',
                dirName: 'rfcs',
            }],
        },
        {
            type: 'link',
            label: 'Charter',
            href: "https://github.com/openbao/openbao/blob/main/CHARTER.md",
        },
    ],
};

export default sidebars;
