compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

pnpmPath: .pnpm/releases/yarn-4.12.0.cjs

preferFrozenLockfile: true
autoInstallPeers: true
strictPeerDependencies: false
shamefullyHoist: false
hoist: true

packageExtensions:
  ember-modal-dialog@*:
    peerDependencies:
      ember-tether: "^3.0.0"

packages:
  - apps/*
  - packages/*
  - tools/*
