// Copyright (c) 2026 OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"reflect"
	"strings"
	"unicode/utf16"
	"unicode/utf8"
)

// RawSecret represents a secret returned by the API, but with a twist:
// All string values are stored as []byte so they can be securely erased.
// Why? Because Go strings are immutable—they stay in memory once created.
// WARNING: Overwriting the []byte NOT clear copies held in HTTP/TLS buffers!
type RawSecret struct {
	// RequestID uniquely identifies the request generated by this response
	// (useful for logging/debugging).
	RequestID string

	// LeaseID is the unique identifier for the lease associated with a secret.
	LeaseID string
	// LeaseDuration is how long (in seconds) the lease is valid.
	LeaseDuration int
	// Renewable indicates whether the lease can be renewed.
	Renewable bool

	// Data contains the actual secret data (e.g., {"password": "s3cr3t"}).
	// Strings are stored as []byte here so they can be securely erased later.
	Data map[string]any

	// Warnings contains non-fatal warnings (e.g., "Deprecated").
	Warnings []string

	// Auth contains optional authentication info.
	Auth *SecretAuth

	// WrapInfo contains info about optional response wrapping.
	WrapInfo *SecretWrapInfo
}

// rawSecretWire is the "raw" variant of RawSecret, as it comes straight from
// the JSON response.
// The key difference: Data stays as raw JSON (json.RawMessage) so we don’t
// accidentally decode strings into Go strings.
type rawSecretWire struct {
	RequestID     string                     `json:"request_id"`
	LeaseID       string                     `json:"lease_id"`
	LeaseDuration int                        `json:"lease_duration"`
	Renewable     bool                       `json:"renewable"`
	Data          map[string]json.RawMessage `json:"data"`
	Warnings      []string                   `json:"warnings"`
	Auth          *SecretAuth                `json:"auth,omitempty"`
	WrapInfo      *SecretWrapInfo            `json:"wrap_info,omitempty"`
}

// --- Public API Functions ---

// ReadBytesWithContext reads a secret from a given path and returns it as
// RawSecret. The context is used for timeouts and cancellation.
func (c *Logical) ReadBytesWithContext(
	ctx context.Context,
	path string,
) (*RawSecret, error) {
	// Simple delegation to ReadBytesWithDataWithContext.
	return c.ReadBytesWithDataWithContext(ctx, path, nil)
}

// ReadBytesWithDataWithContext same as ReadBytesWithContext, but allows
// additional query parameters (e.g., for filtering or options).
func (c *Logical) ReadBytesWithDataWithContext(
	ctx context.Context,
	path string,
	data map[string][]string, // e.g., {"version": {"1"}}
) (*RawSecret, error) {
	// Extend the context with a timeout config and make sure it gets canceled.
	ctx, cancel := c.c.withConfiguredTimeout(ctx)
	defer cancel()

	// Make the actual request to the backend.
	resp, err := c.readRawWithDataWithContext(ctx, path, data)
	// Parse the response and ensure the body is closed.
	return parseAndCloseResponse(resp, err)
}

// --- Internal Helper Functions ---

// parseAndCloseResponse handles parsing the response and closing the response.
func parseAndCloseResponse(resp *Response, err error) (*RawSecret, error) {
	// If there’s no response, there’s no secret.
	if resp == nil {
		return nil, err
	}
	// Always close the body to avoid memory leaks.
	defer resp.Body.Close()

	// Special case: 404, but with warnings or data (e.g., soft delete).
	// A 404 also comes back as an error, so this runs before the error check.
	if resp.StatusCode == 404 {
		secret, parseErr := ParseRawSecret(resp.Body)
		// No empty body but parsing faeils.
		if parseErr != nil && !errors.Is(parseErr, io.EOF) {
			return nil, parseErr
		}
		// If we have a secret with warnings or data, return it.
		if secret != nil && (len(secret.Warnings) > 0 || len(secret.Data) > 0) {
			return secret, nil
		}
		// Otherwise: not found.
		return nil, nil
	}

	if err != nil {
		return nil, err
	}

	return ParseRawSecret(resp.Body)
}

// ParseRawSecret parses the JSON body of a response into a RawSecret.
// Requirement: Strings remain as []byte so they can be securely erased later.
func ParseRawSecret(r io.Reader) (*RawSecret, error) {
	// We might need to read the body twice:
	// 1. First attempt: Parse as rawSecretWire.
	// 2. If that fails: Parse as raw JSON (e.g., for error messages).
	// We use TeeReader to copy the body into a buffer for the second attempt.
	var bodyBuffer, teeBuffer bytes.Buffer
	teeReader := io.TeeReader(r, &teeBuffer)
	if _, err := bodyBuffer.ReadFrom(teeReader); err != nil {
		return nil, err
	}

	// Nothing to parse because body is empty.
	if bodyBuffer.Len() == 0 {
		return nil, nil
	}

	// First, try to parse the response as rawSecretWire.
	var wire rawSecretWire
	decoder := json.NewDecoder(&bodyBuffer)
	decoder.UseNumber() // Parse numbers as json.Number, not float64.
	if err := decoder.Decode(&wire); err != nil {
		return nil, err
	}

	/// Build the RawSecret from the wire format:

	secret := &RawSecret{
		RequestID:     wire.RequestID,
		LeaseID:       wire.LeaseID,
		LeaseDuration: wire.LeaseDuration,
		Renewable:     wire.Renewable,
		Warnings:      wire.Warnings,
		Auth:          wire.Auth,
		WrapInfo:      wire.WrapInfo,
	}

	if wire.Data != nil {
		convertedData, err := convertJSONToRawData(wire.Data)
		if err != nil {
			return nil, err
		}
		secret.Data = convertedData
	}

	// If the wire format is empty, so, the response might be raw JSON
	// (e.g., error messages). This happens when the backend doesn’t return the
	// expected structure.
	if reflect.DeepEqual(wire, rawSecretWire{}) {
		return handleRawJSONResponse(&teeBuffer, secret)
	}

	return secret, nil
}

// handleRawJSONResponse handles responses that are not in the expected
// rawSecretWire format. Happens with raw JSON (e.g., error messages).
func handleRawJSONResponse(
	body *bytes.Buffer,
	secret *RawSecret,
) (*RawSecret, error) {
	var rawData map[string]json.RawMessage
	decoder := json.NewDecoder(body)
	decoder.UseNumber()
	if err := decoder.Decode(&rawData); err != nil {
		return nil, err
	}

	// Case 1: Only errors in the response -> treat as "not found".
	if _, hasErrors := rawData["errors"]; hasErrors && len(rawData) == 1 {
		return nil, nil
	}

	// Case 2: Errors + other data -> return the errors as an error.
	if errRaw, hasErrors := rawData["errors"]; hasErrors {
		var errorMessages []string
		if err := json.Unmarshal(errRaw, &errorMessages); err != nil {
			return nil, err
		}
		return nil, errors.New(strings.Join(errorMessages, " "))
	}

	// Case 3: Data -> convert and use it.
	if len(rawData) > 0 {
		convertedData, err := convertJSONToRawData(rawData)
		if err != nil {
			return nil, err
		}
		secret.Data = convertedData
	}

	return secret, nil
}

// convertJSONToRawData converts a map of raw JSON values.
// Strings are converted to []byte so they can be securely erased later.
func convertJSONToRawData(
	rawData map[string]json.RawMessage,
) (map[string]any, error) {
	result := make(map[string]any, len(rawData))
	for key, rawValue := range rawData {
		convertedValue, err := convertJSONValue(rawValue)
		if err != nil {
			return nil, err
		}
		result[key] = convertedValue
	}
	return result, nil
}

// convertJSONValue converts a single raw JSON value.
// - Strings -> []byte
// - Objects -> map[string]any (recursively)
// - Arrays -> []any (recursively)
// - Booleans/Null/Numbers -> Go equivalents
func convertJSONValue(rawValue json.RawMessage) (any, error) {
	rawValue = bytes.TrimSpace(rawValue)
	if len(rawValue) == 0 {
		return nil, nil
	}

	// The first character tells us the type of the JSON value.
	switch rawValue[0] {
	case '"': // String, e.g., "servus!"
		// Remove quotes and resolve escape sequences.
		return unescapeJSONString(rawValue[1 : len(rawValue)-1]), nil

	case '{': // Object, e.g., {"key": "any value"}
		var obj map[string]json.RawMessage
		if err := json.Unmarshal(rawValue, &obj); err != nil {
			return nil, err
		}
		return convertJSONToRawData(obj)

	case '[': // Array, e.g., [1, 2, 3]
		var arr []json.RawMessage
		if err := json.Unmarshal(rawValue, &arr); err != nil {
			return nil, err
		}
		result := make([]any, len(arr))
		for i, item := range arr {
			converted, err := convertJSONValue(item)
			if err != nil {
				return nil, err
			}
			result[i] = converted
		}
		return result, nil

	case 't': // true
		return true, nil
	case 'f': // false
		return false, nil
	case 'n': // null
		return nil, nil
	default: // Number, e.g., 42 or 13.28
		// Keep numbers as json.Number to avoid losing precisions.
		return json.Number(rawValue), nil
	}
}

// unescapeJSONString removes quotes and resolves escape sequences from a JSON
// string because encoding/json unfortunately doesn’t do this when it comes to
// working with raw JSON.
func unescapeJSONString(raw []byte) []byte {
	result := make([]byte, 0, len(raw))
	for offset := 0; offset < len(raw); {
		char := raw[offset]

		// UTF-8 characters (multiple bytes) -> copy directly.
		if char >= utf8.RuneSelf {
			decoded, width := utf8.DecodeRune(raw[offset:])
			if decoded == utf8.RuneError && width == 1 {
				// Invalid UTF-8: Keep RuneError.
				result = utf8.AppendRune(result, utf8.RuneError)
			} else {
				// Valid UTF-8: Copy directly.
				result = append(result, raw[offset:offset+width]...)
			}
			offset += width
			continue
		}

		// Not an escape character or at the end of the string -> copy as-is.
		if char != '\\' || offset+1 >= len(raw) {
			result = append(result, char)
			offset++
			continue
		}
		offset++ // Skip the backslash.

		// Process the escape sequence.
		switch raw[offset] {
		case 'b': // \b -> backspace
			result = append(result, '\b')
			offset++
		case 'f': // \f -> form feed
			result = append(result, '\f')
			offset++
		case 'n': // \n -> newline
			result = append(result, '\n')
			offset++
		case 'r': // \r -> carriage return
			result = append(result, '\r')
			offset++
		case 't': // \t -> tab
			result = append(result, '\t')
			offset++
		case 'u': // \uXXXX -> Unicode escape
			// Decode \uXXXX (e.g., \u0041 -> 'A').
			decoded := decodeUnicodeEscape(raw[offset-1:])
			if decoded < 0 {
				// Invalid escape -> treat as normal character.
				result = append(result, raw[offset])
				offset++
				continue
			}
			offset += 5 // Skip \uXXXX.

			// Handle UTF-16 surrogate pairs (e.g., for emojis).
			if utf16.IsSurrogate(decoded) {
				// An unpaired surrogate becomes RuneError.
				next := decodeUnicodeEscape(raw[offset:])
				paired := utf16.DecodeRune(decoded, next)
				if paired != utf8.RuneError {
					offset += 6 // Skip the second \uXXXX.
				}
				decoded = paired
			}
			result = utf8.AppendRune(result, decoded)
		default: // Unknown escape -> treat as normal character.
			result = append(result, raw[offset])
			offset++
		}
	}
	return result
}

// decodeUnicodeEscape decodes a \uXXXX escape sequence from a JSON string.
// Returns the decoded rune, or -1 if the sequence is invalid.
func decodeUnicodeEscape(raw []byte) rune {
	// Check if the sequence is long enough and starts with \u.
	if len(raw) < 6 || raw[0] != '\\' || raw[1] != 'u' {
		return -1
	}

	var decoded rune
	// Process each of the 4 characters after \u (XXXX).
	for _, c := range raw[2:6] {
		var value byte
		switch {
		case c >= '0' && c <= '9':
			value = c - '0'
		case c >= 'a' && c <= 'f':
			value = c - 'a' + 10
		case c >= 'A' && c <= 'F':
			value = c - 'A' + 10
		default:
			return -1 // Invalid hex character.
		}
		decoded = decoded*16 + rune(value)
	}
	return decoded
}
