name: Docs CI
on:
  pull_request:
    # The default types for pull_request are [ opened, synchronize, reopened ].
    # This is insufficient for our needs, since we're skipping stuff on PRs in
    # draft mode.  By adding the ready_for_review type, when a draft pr is marked
    # ready, we run everything, including the stuff we'd have skipped up until now.
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "website/**"

jobs:
  check-links:
    name: Check Absolute Links
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Find absolute links
        run: |
          echo "Checking for absolute links in website/content/docs/..."
          grep -rn -P "(\(|: |openbao.org)/docs/[^)]+" website/content/docs > grep_output.txt || true

          echo "Checking for absolute links in website/content/api-docs/..."
          grep -rn -P "(\(|: |openbao.org)/api-docs/[^)]+" website/content/api-docs >> grep_output.txt || true

          # Check if any absolute links were found
          if [ -s grep_output.txt ]; then
            echo "::error::Found absolute links that should be relative. See annotations for details."
            jq -rRs 'split("\n")[:-1][]| split(":") | "::error file=\(.[0]),line=\(.[1]),title=Absolute Link found::\(.[2:]| join(":"))"' grep_output.txt
            exit 1
          fi
  test-docs:
    name: Test Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
        with:
          package_json_file: website/package.json
          cache: true
          cache_dependency_path: website/pnpm-lock.yaml
      - id: build-docs
        name: build-docs
        working-directory: ./website
        run: |
          make build-versioned
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: website
          path: website/build/

  lint-docs:
    name: Lint Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
        with:
          package_json_file: website/package.json
          cache: true
          cache_dependency_path: website/pnpm-lock.yaml
      - id: lint-docs
        name: lint-docs
        working-directory: ./website
        run: |
          make lint
