name: Validate publiccode.yml

on:
  push:
    paths:
      - "publiccode.yml"
      - ".github/workflows/publiccodeyml-check.yml"
  pull_request:
    paths:
      - "publiccode.yml"
      - ".github/workflows/publiccodeyml-check.yml"

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: publiccode.yml validation
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: italia/publiccode-parser-action@21086c73ec0563e14c6748787efa1b34b025ad8c # v1.5.1
        with:
          publiccode: "publiccode.yml"
          no-network: true
