name: Validate publiccode.yml

on:
  push:
    paths:
      - "publiccode.yml"
      - ".github/workflows/publiccodeyml-check.yml"
  pull_request:
    paths:
      - "publiccode.yml"
      - ".github/workflows/publiccodeyml-check.yml"

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: publiccode.yml validation
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: italia/publiccode-parser-action@21086c73ec0563e14c6748787efa1b34b025ad8c # v1.5.1
        with:
          publiccode: "publiccode.yml"
          no-network: true
