name: Release container images

on:
  release:
    types:
      - published

  # The manual trigger can be used to rebuild images based on later based images
  # and packages without creating a new release/tag.
  workflow_dispatch:
    inputs:
      version:
        description: Version to (re-)release, e.g., v2.0.0
        required: true
        type: string
      distro:
        description: Distribution to (re-)release
        default: all
        type: choice
        options:
          - all
          - openbao
          - openbao-distroless
          - openbao-ubi
          - openbao-hsm
          - openbao-hsm-ubi

  # This trigger is called directly by "release.yml" to automatically trigger
  # image releases on nightly releases.
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      distro:
        default: all
        type: string

env:
  # Pick the right version input based on the workflow trigger.
  VERSION: ${{ case(github.event_name == 'release', github.ref_name, inputs.version) }}

permissions:
  contents: read

jobs:
  release:
    name: ${{ matrix.distro.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        distro:
          - name: openbao
            target: default
            include: >-
              ${{
                github.event_name == 'release' ||
                contains(fromJSON('["all", "openbao"]'), inputs.distro)
              }}
            platforms:
              - linux/amd64
              - linux/arm64
              - linux/arm/v6
              - linux/ppc64le
              - linux/riscv64
              - linux/s390x
          - name: openbao-ubi
            target: ubi
            include: >-
              ${{
                github.event_name == 'release' ||
                contains(fromJSON('["all", "openbao-ubi"]'), inputs.distro)
              }}
            platforms:
              - linux/amd64
              - linux/arm64
              - linux/ppc64le
              - linux/s390x
          - name: openbao-distroless
            target: distroless
            include: >-
              ${{
                github.event_name == 'release' ||
                contains(fromJSON('["all", "openbao-distroless"]'), inputs.distro)
              }}
            platforms:
              - linux/amd64
              - linux/arm64
              - linux/arm
              - linux/ppc64le
              - linux/riscv64
              - linux/s390x
          - name: openbao-hsm
            target: default
            include: >-
              ${{
                github.event_name == 'release' ||
                contains(fromJSON('["all", "openbao-hsm"]'), inputs.distro)
              }}
            platforms:
              - linux/amd64
              - linux/arm64
          - name: openbao-hsm-ubi
            target: ubi
            include: >-
              ${{
                github.event_name == 'release' ||
                contains(fromJSON('["all", "openbao-hsm-ubi"]'), inputs.distro)
              }}
            platforms:
              - linux/amd64
              - linux/arm64
        exclude:
          - distro:
              include: false
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-tags: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Determine tags
        id: tags
        run: ./scripts/release/container-tags.sh
        env:
          IMAGE_NAME: ${{ github.repository_owner }}/${{ matrix.distro.name }}${{ case(contains(env.VERSION, 'nightly'), '-nightly', '') }}

      - name: Log into ghcr.io
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        if: contains(fromJSON(steps.tags.outputs.registries), 'ghcr.io')
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into docker.io
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        if: contains(fromJSON(steps.tags.outputs.registries), 'docker.io')
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into quay.io
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        if: contains(fromJSON(steps.tags.outputs.registries), 'quay.io')
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Download release artifacts
        run: |
          ./scripts/release/download-artifacts.sh
          ./scripts/release/extract-linux-binaries.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PATTERN: ${{ case(startsWith(matrix.distro.name, 'openbao-hsm'), 'openbao-hsm', 'openbao') }}_*_linux_*.tar.gz

      - name: Get release info
        id: info
        run: |
          echo "sha=$(git rev-parse "$VERSION")" >> "$GITHUB_OUTPUT"
          echo "epoch=$(git log -1 --format=%ct "$VERSION")" >> "$GITHUB_OUTPUT"
          echo "date=$(TZ=UTC git log -1 --format=%cd --date=iso-strict-local "$VERSION")" >> "$GITHUB_OUTPUT"

      - name: Build and push images
        id: build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: true
          tags: ${{ join(fromJSON(steps.tags.outputs.tags), ',') }}
          target: ${{ matrix.distro.target }}
          platforms: ${{ join(matrix.distro.platforms, ',') }}
          outputs: type=registry,rewrite-timestamp=true
          build-args: SOURCE_DATE_EPOCH=${{ steps.info.outputs.epoch }}
          # We add both "legacy" non-namespaced labels and OCI-standardized
          # labels. Legacy labels are primarily required for Red Hat to certify
          # images based on UBI, but it does not harm to add them to all
          # distributions.
          labels: |
            name=OpenBao
            maintainer=OpenBao <openbao@lists.openssf.org>
            vendor=OpenBao
            version=${{ env.VERSION }}
            release=${{ steps.info.outputs.epoch }}
            build-date=${{ steps.info.outputs.date }}
            summary=OpenBao is a tool for securely accessing secrets
            description=OpenBao is a tool for securely accessing secrets. A secret is anything that you want to tightly control access to, such as API keys, passwords, certificates, and more. OpenBao provides a unified interface to any secret, while providing tight access control and recording a detailed audit log
            url=https://openbao.org
            vcs-ref=${{ steps.info.outputs.sha }}
            vcs-type=git
            org.opencontainers.image.authors=OpenBao <openbao@lists.openssf.org>
            org.opencontainers.image.url=https://openbao.org
            org.opencontainers.image.documentation=https://github.com/openbao/openbao/blob/main/README.md
            org.opencontainers.image.source=https://github.com/openbao/openbao
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.revision=${{ steps.info.outputs.sha }}
            org.opencontainers.image.vendor=OpenBao
            org.opencontainers.image.licenses=MPL-2.0
            org.opencontainers.image.title=OpenBao
            org.opencontainers.image.description=OpenBao is a tool for securely accessing secrets

      - name: Sign images w/ Cosign
        run: |
          images=""
          for tag in $(jq -r '.[]' <<< "$TAGS"); do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
        env:
          TAGS: ${{ steps.tags.outputs.tags }}
          DIGEST: ${{ steps.build.outputs.digest }}
