name: UI CI
on:
  merge_group:
  pull_request:
    # The default types for pull_request are [ opened, synchronize, reopened ].
    # This is insufficient for our needs, since we're skipping stuff on PRs in
    # draft mode.  By adding the ready_for_review type, when a draft pr is marked
    # ready, we run everything, including the stuff we'd have skipped up until now.
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "ui/**"
  push:
    branches:
      - main
      - release/**

jobs:
  test-ui:
    name: Test UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/set-up-go
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ui/package.json
      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
        with:
          package_json_file: ui/package.json
          cache: true
          cache_dependency_path: ui/pnpm-lock.yaml
      - id: install-browser
        uses: browser-actions/setup-chrome@4f8e94349a351df0f048634f25fec36c3c91eded # v2.1.1
      - id: ui-dependencies
        name: ui-dependencies
        working-directory: ./ui
        run: pnpm install
      - id: build-go-dev
        name: build-go-dev
        run: make ci-bootstrap dev
      - id: test-ui
        name: test-ui
        run: |
          export PATH="${PWD}/bin:${PATH}"
          cd ui
          mkdir -p test-results/qunit
          pnpm test
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results-ui
          path: ui/test-results
        if: success() || failure()
      - uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: "ui/test-results/qunit/results.xml"
          show: "fail"
        if: always()
