name: UI CI
on:
  merge_group:
  pull_request:
    # The default types for pull_request are [ opened, synchronize, reopened ].
    # This is insufficient for our needs, since we're skipping stuff on PRs in
    # draft mode.  By adding the ready_for_review type, when a draft pr is marked
    # ready, we run everything, including the stuff we'd have skipped up until now.
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "ui/**"
  push:
    branches:
      - main
      - release/**
    paths:
      - "ui/**"
  workflow_dispatch:

jobs:
  test-ui:
    name: Test UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/set-up-go
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ui/package.json
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: ui/package.json
          cache: true
          cache_dependency_path: ui/pnpm-lock.yaml
      - id: install-browser
        uses: browser-actions/setup-chrome@2e1d749697dd1612b833dba4a722266286fbefcd # v2.1.2
      - id: ui-dependencies
        name: ui-dependencies
        working-directory: ./ui
        run: pnpm install
      - id: build-go-dev
        name: build-go-dev
        run: make dev
      - id: test-ui
        name: test-ui
        run: |
          export PATH="${PWD}/bin:${PATH}"
          cd ui
          mkdir -p test-results/qunit
          pnpm test
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results-ui
          path: ui/test-results
        if: success() || failure()
      - uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2.6
        with:
          paths: "ui/test-results/qunit/results.xml"
          show: "fail"
        if: always()
